# Generated by Django 5.0.14 on 2026-07-28 11:23

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashback_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cashback_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cash_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashback_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('reversal', 'Reversal')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=10)),
                ('no_cashback', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.transaction')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_txn_idempotency_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('check_amount__gte', 0)), name='txn_check_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('cashback_earned__gte', 0)), name='txn_cashback_earned_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('cashback_spent__gte', 0)), name='txn_cashback_spent_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('cash_paid__gte', 0)), name='txn_cash_paid_gte_0'),
        ),
    ]
