# Generated by Django 5.0.14 on 2026-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_userprofile_full_name_and_more'),
        ('customers', '0005_customer_language'),
        ('ledger', '0002_transaction_flagged_transaction_suspicion_score'),
        ('tenants', '0005_globalsettings_platform_logo_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'seller', 'created_at'], name='txn_tenant_seller_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='txn_tenant_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'created_at'], name='txn_tenant_created_idx'),
        ),
    ]
