# Generated by Django 5.0.14 on 2026-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('superadmin', 'Superadmin'), ('tenant_admin', 'Tenant Admin'), ('branch_manager', 'Branch Manager'), ('seller', 'Seller')], default='unassigned', max_length=20),
        ),
    ]
