# Generated by Django 5.0.14 on 2026-07-28 11:23

import apps.customers.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format, e.g. +998901234567.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField(default=apps.customers.models.default_pending_cashback_expiry)),
                ('claimed', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be E.164 format, e.g. +998901234567.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.customers.models.generate_otp_code, max_length=6)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField(default=apps.customers.models.default_otp_expiry)),
                ('used', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
