# Generated by Django 5.0.14 on 2026-07-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('ledger', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcashback',
            name='source_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_cashbacks', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='pendingcashback',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_customer_phone_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_id__isnull', False)), fields=('tenant', 'telegram_id'), name='unique_customer_telegram_id_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.CheckConstraint(check=models.Q(('amount_requested__gte', 0)), name='otp_amount_requested_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='pendingcashback',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='pending_cashback_amount_gte_0'),
        ),
    ]
