# Generated by Django 5.0.14 on 2026-07-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0003_pendingcashback_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcashback',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pending_cashbacks', to='accounts.branch'),
            preserve_default=False,
        ),
    ]
