# Generated by Django 5.0.14 on 2026-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_pendingcashback_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2),
        ),
    ]
