# Generated by Django 5.0.14 on 2026-07-28 10:33

import apps.tenants.models
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cashback_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('max_redeem_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('max_check_amount', models.DecimalField(decimal_places=2, default=Decimal('2000000.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Global settings',
                'verbose_name_plural': 'Global settings',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cashback_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_redeem_amount', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=12)),
                ('points_expiry_days', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=64)),
                ('webhook_secret', models.CharField(default=apps.tenants.models.generate_webhook_secret, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'base_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
