# Generated by Django 5.0.14 on 2026-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='max_daily_redemptions_per_customer',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_daily_txn_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Default per-seller daily transaction cap for this tenant. Null = unlimited. A Seller.daily_txn_limit, when set, overrides this.', null=True),
        ),
    ]
