# Generated by Django 5.0.14 on 2026-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_globalsettings_max_daily_redemptions_per_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='broadcast_quota',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Max broadcasts a tenant can send per calendar month, shared across all its tenant_admin logins. Null = unlimited.', null=True),
        ),
    ]
