# Generated by Django 5.0.14 on 2026-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_broadcast_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='branch_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Max branches this tenant's admin can create in total (CLAUDE.md-adjacent monetization lever, same shape as broadcast_quota). Null = unlimited.", null=True),
        ),
    ]
