# Generated by Django 5.0.14 on 2026-08-12 10:08

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_branch_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='platform_logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.tenants.models.platform_logo_upload_path),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='platform_name',
            field=models.CharField(default='Pharmacy Cashback', help_text="Product-wide brand name shown on the login screen and in the superadmin's own account (every tenant-scoped account sees its own Tenant.name/logo instead — see Tenant.name/Tenant.logo).", max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.tenants.models.tenant_logo_upload_path),
        ),
    ]
