# Generated by Django 5.0.14 on 2026-08-14 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_language'),
        ('tenants', '0005_globalsettings_platform_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='receipt_branch',
            field=models.ForeignKey(blank=True, help_text='QR-chek orqali kelgan cashback shu filialga yoziladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_tin',
            field=models.CharField(blank=True, default='', help_text="Bu dorixonaning STIR raqami — QR-chek orqali cashback faqat shu STIR'ga tegishli cheklar uchun ishlaydi. Bo'sh bo'lsa, botda QR-chek funksiyasi o'chirilgan.", max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', "STIR 9 ta raqamdan iborat bo'lishi kerak.")]),
        ),
    ]
